export const environment = {
 production: true,
 extension:"+1",
 companylogo:"",
 timesheet:"https://testfunctionappadfb.blob.core.windows.net/timesheets/",
 userLogin: "https://projectdeskprd.azurewebsites.net/api/UserLogin",
 verifyMobile : "https://projectdeskprd.azurewebsites.net/api/VerifyMobile?code=6RXFo7dLncuywI0udjko36QT3jHrmgFR07xXHd5SaPiY03Rldqjpnw==",
 imageUpload: "https://projectdeskprd.azurewebsites.net/api/ImageUpload?code=H7JVVGbY2WQg5lduQDZ5tr6cgXGvmOULCpD9wQryywEVO0bww1ToTg==",
 registerCompany : "https://projectdeskprd.azurewebsites.net/api/RegisterCompany?code=TAqmiOpK7ASYDm3KpcQsor5jcXJpaeuy8EgACvaoeduHSNUNF8VdHQ==",
 resetPassword :"https://projectdeskprd.azurewebsites.net/api/ResetPassword?code=FYRMK7Z5WgawT3KU7nceAsZ9TPdmus6frsYrm3KCg0QvoaSU3bJcmQ==",
 forgotPassword:"https://projectdeskprd.azurewebsites.net/api/ForgotPassword?code=CBQkO3ww/n0wHF69MrScRAwiNj2Af0eZJpPphSPjTj1Utv2nD7YKHA==",
 emailVerificationUserRegistration:"https://projectdeskprd.azurewebsites.net/api/EmailVerificationForUserRegistration?code=t3pHbq3ceLoFysq6uUjhcQQSA0VtvJBwWF3sLUuVNOLC/xe90rIHOA==",
 registerUser:"https://projectdeskprd.azurewebsites.net/api/RegisterUser?code=77IYUhJJq27qkfffZibcSXm2y2bFuriaUjzaHcspqFTukpq9PBzkow==",
 checkCompanyValidity:"https://projectdeskprd.azurewebsites.net/api/CheckCompanyName?code=qZqf7eBxW1QTSo5S9GdxhbDLjfOnaRsC7xzySyymCSYp80skCIUIsA==",
 getAllPolicies:"https://projectdeskprd.azurewebsites.net/api/GetAllPolicies?code=uNQLnAJ25Gabj/SS7x/SabgY7zPHvJ5G/X3BbSX4oa/mR5q5McX3LQ==",
 deletePolicy:"https://projectdeskprd.azurewebsites.net/api/DeletePolicy?code=3PeW16Lr88R30d1h9aF42oZ9Z7l5NQThKq3XyfuGbMd/OLEqrCAY0Q==",
 editPolicyComponents:"https://projectdeskprd.azurewebsites.net/api/EditPolicyComponents?code=fxHMYpoKBkqWiKEFpuPUmAtzEBk6u3oBAh/ZKcXggbpLL6BTL7SLhQ==",
 editPolicyND:"https://projectdeskprd.azurewebsites.net/api/EditPolicyND?code=IEOSxQE1QJ8CLGDWLwcwgua4IVVQMgGLHJeowRQBfqHIz7wxZiXzqg==",
 createPolicy:"https://projectdeskprd.azurewebsites.net/api/CreatePolicy?code=BqXzwaVHiY7iVigYPnhqi0OiYFyAXDvgpxfaVnU1fJpymzGhrhRQ2A==",
 getAllRoles:"https://projectdeskprd.azurewebsites.net/api/GetAllRoles?code=DQVYo/VH8CmutFL4Eucf5PO1lIA1mxuukt8g5EBI00Rr63wbKxuoaw==",
 deleteRole:"https://projectdeskprd.azurewebsites.net/api/DeleteRole?code=/pdfTGbQkoCagdp7NjSP49hX09eX3soUNfrUwUwAeBMBB4y3FEJzLw==",
 editRoleComponents:"https://projectdeskprd.azurewebsites.net/api/EditRoleHasPolicy?code=5nM9cJRS4LwACRVXlhL7arOGoJbojkdhtPEN4k1OWFkz6xWQ3yzN2g==",
 editRoleND:"https://projectdeskprd.azurewebsites.net/api/EditRoleND?code=UT7DvQhVAWZPAIJwzMNuScP4TpSBXtfjLtdLaAlXKMcV0dhV0kOZ8Q==",
 createRole:"https://projectdeskprd.azurewebsites.net/api/CreateRole?code=gNcp15sUBqdxItgJQv1aiCKS5jiSwFeWrtvxKU36KCJTyj0kwa0IdA==",
 roleHasPolicyList:"https://projectdeskprd.azurewebsites.net/api/RolehasPolicyList?code=3a9rtyzxVU6mwXKa6O0xvwX4vkaWx8/LVREuBrVcaso9URGN6AnlVw==",
 getAllUsersinCompany: "https://projectdeskprd.azurewebsites.net/api/GetAllUsersInCompany?code=qhxk652qaXbwDEtZILTjHpr5dSGYruvsHveVGh9QqzaXXJlfYJhCUA==",
 getAllGroups:"https://projectdeskprd.azurewebsites.net/api/GetAllGroups?code=O6WBfZ6nKRpUXzCLWq4k7ZTDLzfrgXtMl6RU91RHZ4nV45jpGL1ZqQ==",
 createGroup:"https://projectdeskprd.azurewebsites.net/api/CreateGroup?code=v8T/5Gpt8azpWN677tGG4TrBG/KgE/CD9GKxGzcUNxSQw5RWWMxwvQ==",
 deleteGroups:"https://projectdeskprd.azurewebsites.net/api/DeleteGroups?code=2mRuO0anXl1uuwnalsk4E4wamO1CilAAbAy84Wtar8gWgOf5GHSGLw==",
 editGroupND:"https://projectdeskprd.azurewebsites.net/api/EditGroupND?code=MDziqnlkxZmxSnFU4jKIxi34php7/gg23elwNnzjxKWL2qFJi94taA==",
 editGroupHasPolicyorRole:"https://projectdeskprd.azurewebsites.net/api/EditGroupHasPolicyorRole?code=x6PD9L6Rvg2waBDdqo/K1Tc3790h/aNbwXeTaritadU1zvYu6J8oBQ==",
 editGroupHasUsers:"https://projectdeskprd.azurewebsites.net/api/EditGrouphasUsers?code=jjf7kdoJCiXvQoAvyEVliOVEAHSrlbChAqzIgwsQCWvWUMn/Wysm4g==",
 grouphasRolesList:"https://projectdeskprd.azurewebsites.net/api/GrouphasRoles?code=cM7amBbkmcGX5WLPpy6KrnBRPGMrVtAlwVsPC3MGLAMHaCN3EhWpqw==",
 grouphasPoliciesList:"https://projectdeskprd.azurewebsites.net/api/GrouphasPolicies?code=YBm2CwfgInjpsDkOF5FieF0DNE81Kg52dXm1u/aI0PdLmH0p43XYGg==",
 grouphasUsersList:"https://projectdeskprd.azurewebsites.net/api/GrouphasUsers?code=d6BRsVzchsenaNE61aSwIoD08tMwV5zT7mTEXzDVtdjSs5TIbaE0rA==",
 getComponentCounts:"https://projectdeskprd.azurewebsites.net/api/GetComponentCounts?code=4qSCzJeXUUhsTv0mEn3n6vi2T5ozOyKfudAvmG38k95vonGZ0CE9tw==",
 AddUsertoCompany:"https://projectdeskprd.azurewebsites.net/api/AddUsertoCompany?code=VKiIhBZ4hR2Xqn8tb3m1xY8aQzfwSmfJBCb/3YynxFFF331bgiffIw==",
 EditUserPrivileges:"https://projectdeskprd.azurewebsites.net/api/EditUserPrivileges?code=0SSEkW1tx7Y5nRcZ0Ok/QukozEb5/HklfGkbuqncMPZ60q44QUjnDA==",
 RemoveUserFromCompany:"https://projectdeskprd.azurewebsites.net/api/RemoveUserFromCompany?code=NhbjAiDLvZeGQSQyaNwK9siblsfgwktFGONRq66ujkAKQliJCqEiOg==",
 getAllUsers:"https://projectdeskprd.azurewebsites.net/api/GetAllUsers?code=PNswzpWLPAKzUSqIkrDyZWiofaI9djb7KxaxYdX2ECSsfvKFKctzUg==",
 UserhasPoliciesList:"https://projectdeskprd.azurewebsites.net/api/UserhasPolicies?code=lTy3TuythCalLoXgAhWnZLmc9x09PVOgIxdlV/2F0YL44ESvd8ZAAA==",
 UserhasRolesList:"https://projectdeskprd.azurewebsites.net/api/UserhasRoles?code=iMm0RayQxuCj0hLkpf1fy9/E2mwMcnVGCYlf3DmkCWVQKSb54tHATw==",
 UserhasGroupsList:"https://projectdeskprd.azurewebsites.net/api/UserhasGroups?code=em8HZrEubRlsAgyr3Yv/G7sNY5p1MqtcTvQ20aKJ2TFbjHtInZ2agA==",
 InviteUsertoRegister:"https://projectdeskprd.azurewebsites.net/api/InviteUsertoRegister?code=OGNW78Hm2awMpSaUE8QFtOFX9aby8KcNRBSUZlgFCNo54uEa88oEDA==",
 registerUserInvited:"https://projectdeskprd.azurewebsites.net/api/RegisterUserInvited?code=ae46Z3akOauU9kfa2EnM4csgP9EE06kPQV7tyVWTjkGs9iDHYOQmWQ==",
 getUserNotinCompany:"https://projectdeskprd.azurewebsites.net/api/getAllUsersNotinCompany?code=40YERwInh0bdTuMU76Ng8YaSQZWp/mXiS5i7nrb3HTzU5tW18vIW7w==",
 RemovePolicyFromRole:"https://projectdeskprd.azurewebsites.net/api/RemovePolicyFromRole?code=3bqgw9OtoHmiiitGxvSZGndI5nsyJ9hX4pJ6p5oGtb6V9HoKICMPrg==",
 RemoveUserPrivileges:"https://projectdeskprd.azurewebsites.net/api/RemoveUserPrivileges?code=hYFVLG9fsYDr/8HQiCVWb2guRwNYhQOGo13RULktOHkqyCVK3gTatQ==",
 removePolicyorRoleFromGroup:"https://projectdeskprd.azurewebsites.net/api/RemovePolicyorRoleFromGroup?code=SwaZb5lsmHAGGKRatqrUWop1uaF/77MOjRX68nYhwK6q5a3NZS026g==",
 getUserCompanies:"https://projectdeskprd.azurewebsites.net/api/getUserCompanies?code=atR6f2VZarzjlgI3IJKa6O5ZAxmtjyVIO5wHJCDiWpgyvGDt6CyipQ==",
 createProject:"https://projectdeskprd.azurewebsites.net/api/CreateProject?code=AM/APhUa/McQBiDQVFgj7jNPPvOdLruz1jqrUrVJa64O7LgtgHQXMw==",
 editProject:"https://projectdeskprd.azurewebsites.net/api/EditProject?code=fsEtGGgWaQLeWj5xq84czubnJO9pbwAda5WvHLPU0Vvc1fI9i8vRUA==",
 getAllProjects:"https://projectdeskprd.azurewebsites.net/api/GetAllProjects?code=NbYWIUOBgw0IsLReL6VQvpOz4aX/H9MQy5RzjThrFm7zdtoS0Nogmw==",
 deleteProjects:"https://projectdeskprd.azurewebsites.net/api/DeleteProjects?code=fM0nFGYalOsszGsaIifumM2MSZFHo7wkUSlQw/jt6zarlq1x5N5Xtw==",
 projecthasUser:"https://projectdeskprd.azurewebsites.net/api/ProjecthasUsers?code=lyW/o3Ms7Gm4DP8tz6Yb1buSeXbbk6UGxE5N837mxS9foB6OTaTXrg==",
 editProjecthasUser:"https://projectdeskprd.azurewebsites.net/api/EditProjecthasUser?code=0moDoEpCnzaBtkkrr9ENY2QV3L1pWsqVd7l3FVOQaavHxzpSm/5/yQ==",
 removeUserFromProject:"https://projectdeskprd.azurewebsites.net/api/RemoveUserFromProject?code=uSD2YgF8yyT9luAOmQsQaxDvEZJEyu5R0mFvOWE3rU145K4g/ZTxUw==",
 createTask:"https://projectdeskprd.azurewebsites.net/api/CreateTask?code=IdUQk87NgUy6ObKutXUPOPlbabDp0JbZ/T3FK8rU6c9OMvZAgeCBQA==",
 projecthasTask:"https://projectdeskprd.azurewebsites.net/api/ProjecthasTasks?code=5J9jtnBsztym2sVrI6AtfXRNfRxlwPOsGKnqgBtZIOOtY1JWBgEcHA==",
 removeTaskFromProject:"https://projectdeskprd.azurewebsites.net/api/RemoveTaskFromProject?code=VZKxzVa2IqiEpx9o904NRelaOov06AL0lEwwlkij9V85lDou71TkbA==",
 createSubTask:"https://projectdeskprd.azurewebsites.net/api/CreateSubTask?code=ot/KdKGln1q8AOMpHL6xk8P0lF50pjLu1n0obZ6h6l5xnKyJLCojbA==",
 projecthasSubTask:"https://projectdeskprd.azurewebsites.net/api/ProjecthasSubTasks?code=3Nf7metPqQ3K5oifak59ICFlb4ehCB2LBGm8mXi45jzwioareOOdhQ==",
 editSubTask:"https://projectdeskprd.azurewebsites.net/api/EditSubTask?code=DPAi0ZMabXVmkYY5Kgow72UgtadS8Iz6EMjkyEa2qh7OgdpsFObktw==",
 userhasProjects:"https://projectdeskprd.azurewebsites.net/api/UserhasProjects?code=6toCoPQi4x3RHwAta7dbuPYKdvxEWRWso3Bz0xaISXAhgpLG0avlOA==",
 userhasTasks:"https://projectdeskprd.azurewebsites.net/api/UserhasTasks?code=xVINTbGA3UnDGzaHnUUg6judsLpHXvbXVFQjZsyf/00fBMUzDqJEGw==",
 saveTimeLog:"https://projectdeskprd.azurewebsites.net/api/SaveTimeLog?code=1EMsDtBVEnqWIJyRuUAIqVExgyIadrYjMlxdNxIpPVDvbIo/nBeARw==",
 userTimeLogs:"https://projectdeskprd.azurewebsites.net/api/UserTimeLogs?code=55RGkSp/4ggAPjrgAeRQip3IiwR2wv5X/g5XPXX5SQv/YThsumXPwA==",
 editTimeLog:"https://projectdeskprd.azurewebsites.net/api/EditTimelog?code=DPAi0ZMabXVmkYY5Kgow72UgtadS8Iz6EMjkyEa2qh7OgdpsFObktw==",
 deleteTimelogs:"https://projectdeskprd.azurewebsites.net/api/DeleteTimelogs?code=KZSujIR/XnnTD6s2bBio/1Se1L/Qok6jtOtlaK2KbMPPabKemFAkYA==",
 timesheetPDFUpload:"https://projectdeskprd.azurewebsites.net/api/TimesheetPDFUpload?code=8MoF2ywHLNaF9/7qUGbTBEIgFry66d/vWprr0g1NEbTw63dDiLat5g==",
 submitTimesheet:"https://projectdeskprd.azurewebsites.net/api/SubmitTimesheet?code=N3XxHETJYqmNo0DhFMZsUTmRWlgbwzvB/Bxj1hWm79OGv1dqHiOdTQ==",
 userTimesheets:"https://projectdeskprd.azurewebsites.net/api/UserTimesheets?code=NQgqLdlgxK4xrnuLtn4Kd4gcxuGtaBufrRAdclAJTiTRZFgvZSaucA==",
 projectTimesheets:"https://projectdeskprd.azurewebsites.net/api/ProjectTimesheets?code=uHGuPmiHIH04P1zasyz1ZC5qLMC73m2nWQkea/ZB7yIkJyxcaqR6aQ==",
 approveTimesheets:"https://projectdeskprd.azurewebsites.net/api/ApproveTimesheets?code=vwq1cLmeFNpEYzh3Gf3u/UpSDa1xxhbAtiSaltaP8HChZ6QA7KgM2Q==",
 rejectTimesheets:"https://projectdeskprd.azurewebsites.net/api/RejectTimesheets?code=7B59DAsa10UmyMnBBTZFkRvBfbBPjDTIhubpfM7nH6uK9ZsK23E8Bg==",
 rejectedTimelogs:"https://projectdeskprd.azurewebsites.net/api/RejectedTimelogs?code=aW3fM5i7C5GaUAW/gMj7dJJM86xgZuhlCCyPX6eTu0EGWKB3aen32w==",
 reSubmitTimesheet:"https://projectdeskprd.azurewebsites.net/api/ReSubmitTimesheet?code=xnMMM7CONNF2bLRp7CAPnb8A7zPoRxl4T7oCCCsrnQtcRrQATwCVpQ==",
 userPrivileges:"https://projectdeskprd.azurewebsites.net/api/GetUserPrivileges?code=K4kCUnMJ44DrgNhcTvwJbePqnKpNfbxjdp5058JTpRULLr1gTeZ2WA=="
};